In [1]:
def load_articles():
    return ["international", "sports", "sports", "international", "politics"]

def load_ratings():
    return ["good", "very good", "bad", "average", "good"]

In [2]:
from sklearn import preprocessing
data = load_articles()
enc = preprocessing.LabelEncoder()
enc.fit(data)
enc.transform(data)

array([0, 2, 2, 0, 1])

In [3]:
from sklearn import preprocessing

enc = preprocessing.LabelEncoder()
enc.fit(data)
enc.transform(data)

array([0, 2, 2, 0, 1])

In [4]:
import pandas as pd

data = load_ratings()
categories = ['very bad', 'bad', 'average', 'good', 'very good']

data = pd.Categorical(data, categories=categories, ordered=True)
print(data.codes)

[3 4 1 2 3]


In [5]:
from sklearn import preprocessing
data = [load_articles()]

enc = preprocessing.OneHotEncoder()
enc.fit(data)
enc.transform(data)

<1x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>