In [9]:
from transformers import pipeline
classifier = pipeline("sentiment-analysis")

result = classifier("Azure ML is quite good.")[0]
print("Label: %s, with score: %.2f" % (result['label'], result['score']))

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are 

Label: POSITIVE, with score: 1.00


In [10]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

inputs = tokenizer("Azure ML is quite good.", return_tensors="tf")
inputs

{'input_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  101,   138, 26395,   150,  2162,  1110,  2385,  1363,   119,
          102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [11]:
from transformers import TFBertModel

model = TFBertModel.from_pretrained('bert-base-uncased')

outputs = model(**inputs)
outputs.last_hidden_state

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


<tf.Tensor: shape=(1, 10, 768), dtype=float32, numpy=
array([[[-0.30760652,  0.19552925,  0.1440584 , ...,  0.08283961,
          0.16151786,  0.23049755],
        [-0.06404103, -0.00801515,  0.089001  , ...,  0.11718617,
         -0.02273736,  0.1343386 ],
        [-0.3168836 , -0.02516797,  0.19571334, ..., -0.26825368,
          0.22008714, -0.08459515],
        ...,
        [-0.42210063, -0.16916198,  0.33503917, ...,  0.42435306,
          0.10056192, -0.08133757],
        [-0.61650807, -0.33403447, -0.24236108, ...,  0.67485374,
          0.349685  , -0.10853981],
        [ 0.68791753,  0.30658254, -0.41637605, ...,  0.00951517,
         -0.85239846, -0.20786308]]], dtype=float32)>

In [20]:
import pandas as pd

def load_sentiment_data(path, encoder=None):
    df = pd.read_csv(path, sep="\t")
    X = df['Phrase'].values
    y_raw = df['Sentiment'].values
    y = pd.get_dummies(y_raw)
    return X, y

X_train, y_train = load_sentiment_data("data/train.tsv")

inputs = tokenizer(X_train.tolist(), padding=True, truncation=True, return_tensors="tf")
inputs

{'input_ids': <tf.Tensor: shape=(156060, 84), dtype=int32, numpy=
array([[  101,   138,  1326, ...,     0,     0,     0],
       [  101,   138,  1326, ...,     0,     0,     0],
       [  101,   138,  1326, ...,     0,     0,     0],
       ...,
       [  101,   170, 25247, ...,     0,     0,     0],
       [  101,   170, 25247, ...,     0,     0,     0],
       [  101, 22572, 12148, ...,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(156060, 84), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(156060, 84), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype

In [4]:
from transformers import TFBertModel

model = TFBertModel.from_pretrained('bert-base-uncased')

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [23]:
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
last_hidden_states